# TOML file for sample-gosu-app.
# This file is used for the Docker container.
BaseURL = "http://localhost:8000"
PostgresDataSource = "sslmode=disable dbname=sga user=sga"
SessionKey = "11111111111111111111111111111111"
OAuthStateString = "11111111111111111111111111111111"
